version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - dev.env
    command:
      ['start', '8000']

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=financial
      - POSTGRES_DB=financial
      - POSTGRES_PASSWORD=financial
