"""initial

Revision ID: fa2903322bcf
Revises: 
Create Date: 2023-02-26 23:45:11.997730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2903322bcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_data',
    sa.Column('symbol', sa.String(length=5), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.DECIMAL(), nullable=False),
    sa.Column('close_price', sa.DECIMAL(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_data')
    # ### end Alembic commands ###
