"""initial

Revision ID: bd61d04d91ed
Revises: 
Create Date: 2023-02-25 20:22:50.078290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd61d04d91ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.DECIMAL(), nullable=False),
    sa.Column('close_price', sa.DECIMAL(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_symbol_date', 'financial_data', ['symbol', 'date'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_symbol_date', table_name='financial_data')
    op.drop_table('financial_data')
    # ### end Alembic commands ###
